version: "2.0"
volumes:
  applog:
  sharedata:
services:
  app:
    container_name: app-dev
    build:
      context: ./testbed
      dockerfile: dockerfile.ini
    image: app-dev:docker-compose
    volumes:
      - applog:/var/log
      - sharedata:/data
    privileged: true
    ports:
      - 5000:5000